version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: peterlai/get-started:part1
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "82:82"
    networks:
      - webnet
networks:
  webnet: